name: Build Lenovo Tab M8 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Toolchain
        run: |
          sudo apt update
          sudo apt install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev zip ccache gcc-aarch64-linux-gnu

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # اختيار defconfig واستكمال التجميع
          make akita_row_call_defconfig || make mt6761_defconfig
          make -j$(nproc) || make -j2

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz-dtb
          path: arch/arm64/boot/Image*
